name: lbp
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.31+32

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  onesignal_flutter: ^2.6.3
  url_launcher: ^6.0.2
  uuid: 2.2.2
  device_info: ^0.4.0+4
  shared_preferences: ^0.5.2
  gsheets: ^0.2.6
  preferences: ^5.2.0 # preference screen
  provider: ^3.1.0
  footer: ^0.0.3
  intl: ^0.16.1
  date_format: ^1.0.6
  progress_indicator_button: ^0.0.3
  firebase_crashlytics: ^1.0.0
  webfeed: ^0.4.2
  http: ^0.12.2
  hive: ^1.0.0
  hive_flutter: ^0.2.1
  # For OS-specific directory paths
  path_provider: ^1.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.5.1
  build_runner:

flutter:
  uses-material-design: true
  assets:
     - images/
     - images/exercises/cobra_lift.jpg

  fonts:
   - family: Raleway
     fonts:
       - asset: fonts/Raleway-Regular.ttf
       - asset: fonts/Raleway-Thin.ttf
         style: normal

